#!/bin/bash

# --- Resource Requests ---
#SBATCH --job-name=IG_Chain
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:1
#SBATCH --time=4:00:00

# Usage: sbatch submit_iterative_chain.sh <config_step1.json> <config_step2.json>

# --- 1. Load Environment ---
module load anaconda3  
eval "$(conda shell.bash hook)"
conda activate cuda_env

# --- 2. Setup Variables ---
CONFIG_STEP1="$1"
CONFIG_STEP2="$2"

if [ -z "$CONFIG_STEP1" ] || [ -z "$CONFIG_STEP2" ]; then
    echo "Error: Two config files required."
    echo "Usage: $0 <config_step1.json> <config_step2.json>"
    exit 1
fi

# Get the run directory from config step 1 (assuming it's passed as full path or relative)
# We can't easily parse it with bash without jq, so we'll inspect the file location
RUN_DIR=$(dirname "$CONFIG_STEP1")

echo "=================================================="
echo "Job Started on $(hostname) at $(date)"
echo "Config Step 1: $CONFIG_STEP1"
echo "Config Step 2: $CONFIG_STEP2"
echo "Run Directory: $RUN_DIR"
echo "=================================================="

# --- 3. Step 1: Iterative K-Means ---
echo ">>> Starting Step 1: Iterative K-Means Code Generation..."
start_time_1=$(date +%s)

./IndexGen --config "$CONFIG_STEP1"
status_1=$?

end_time_1=$(date +%s)
duration_1=$((end_time_1 - start_time_1))

if [ $status_1 -ne 0 ]; then
    echo "!!! Step 1 Failed with exit code $status_1. Aborting chain."
    exit $status_1
fi

echo ">>> Step 1 Completed in $duration_1 seconds."
echo "--------------------------------------------------"

# --- 4. Intermediate: Find Output File and Update Step 2 Config ---
echo ">>> Finding output file..."
# Expected pattern: CodeSize-*_CodeLen-11_MinED-3.txt
# We search in the run directory.
FOUND_FILE=$(ls "$RUN_DIR"/CodeSize-*_CodeLen-11_MinED-3.txt | head -n 1)

if [ -z "$FOUND_FILE" ]; then
    echo "!!! Error: Could not find output file matching pattern in $RUN_DIR."
    ls -l "$RUN_DIR"
    exit 1
fi

echo ">>> Found output file: $FOUND_FILE"
echo ">>> Updating Config Step 2..."

python3 -c "
import json
import sys

config_path = '$CONFIG_STEP2'
input_file = '$FOUND_FILE'

try:
    with open(config_path, 'r') as f:
        data = json.load(f)
    
    # Update the input file path for FileRead
    # Note: We assume the structure exists as generated by the orchestrator
    data['method']['fileRead']['input_file'] = input_file
    
    with open(config_path, 'w') as f:
        json.dump(data, f, indent=4)
    print(f'Successfully updated {config_path} with input_file={input_file}')
except Exception as e:
    print(f'Error updating config: {e}')
    sys.exit(1)
"

if [ $? -ne 0 ]; then
    echo "!!! Failed to update Step 2 configuration."
    exit 1
fi

# --- 5. Step 2: FileRead Refinement ---
echo "--------------------------------------------------"
echo ">>> Starting Step 2: FileRead Refinement..."
start_time_2=$(date +%s)

./IndexGen --config "$CONFIG_STEP2"
status_2=$?

end_time_2=$(date +%s)
duration_2=$((end_time_2 - start_time_2))

if [ $status_2 -ne 0 ]; then
    echo "!!! Step 2 Failed with exit code $status_2."
    exit $status_2
fi

echo ">>> Step 2 Completed in $duration_2 seconds."
echo "=================================================="
echo "Chain Completed Successfully at $(date)"
